platform :ios, '14.0'

target 'AardvarkRevealDemo' do
  use_frameworks!

  pod 'AardvarkReveal', testspecs: ['UnitTests'], :path => '../AardvarkReveal.podspec'

  pod 'Aardvark', '~> 5.0'
  pod 'AardvarkMailUI', '~> 2.0'
  pod 'CoreAardvark', '~> 4.0'

  pod 'Reveal-SDK'
end
